"""
    IDAPython import script (generated by ukingidatool)
    In IDA, choose File > Script file... or press Alt+F7 to run this script

    The script is generated by using the data and options in comments below:
"""

